version: 2.1

orbs:
  newman: postman/newman@1.0.0

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0

    environment:
      MSBUILDDISABLENODEREUSE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      MSBUILDTERMINALLOGGER: false

    steps:
      - checkout

      - run:
          name: Restore dependencies
          command: dotnet restore

      - run:
          name: Build solution
          command: dotnet build --no-restore --configuration Release

      - run:
          name: Run integration tests and collect results
          command: |
            mkdir -p TestResults
            dotnet test --no-build --configuration Release \
              --logger "trx;LogFileName=test-results.trx" \
              --results-directory TestResults \
              --verbosity quiet

      - store_test_results:
          path: TestResults

      - store_artifacts:
          path: TestResults
          destination: test-results

  run_postman_tests:
    docker:
      - image: node:16

    environment:
      token: $AIRPORT_GAP_API_TOKEN

    steps:
      - checkout
      - run:
          name: Install Newman
          command: npm install -g newman

      - run:
          name: Run Postman Collection
          command: newman run "./Postman.IntegrationTests/AirportGapTests.postman_collection.json" --env-var "token=${AIRPORT_GAP_API_TOKEN}"

workflows:
  version: 2
  run-api-tests:
    jobs:
      - test
      - run_postman_tests
