name: Run UI Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AIRPORT_GAP_API_TOKEN: ${{ secrets.AIRPORT_GAP_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests and save results
        run: |
          mkdir -p TestResults
          dotnet test --no-build --configuration Release \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory TestResults

      - name: Upload test result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/test-results.trx
