name: Run Api Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build-test-analyze:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest

    env:
      AIRPORT_GAP_API_TOKEN: ${{ secrets.AIRPORT_GAP_API_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Set up PATH for .NET tools
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"BrandonNaidoo_airportgap-apiintegration-tests" \
            /o:"brandonnaidoo" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release


      - name: Run POSTMAN collection
        run: |
          newman run "./Postman.IntegrationTests/AirportGapTests.postman_collection.json" --env-var "token=$AIRPORT_GAP_API_TOKEN"

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"